### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by benjamin920101** [Carnations-Botanica/VMHide#1]
How to install it in hackintosh?
Thank you🙏

**Comment by royalgraphx** [comment]
I unfortunately do not understand the question, this kernel extension is for use when macOS is a guest on a hypervisor, i.e a virtual machine like QEMU under KVM on Linux hosts.

**Comment by royalgraphx** [comment]
The issues section of this Github repository is unfortunately not for use as a forum for questions, please redirect questions to the [DarwinKVM](https://discord.gg/ryQFC8Vk7b) server. As of now, while VMHide is much closer to final release, it is still in active development and users are intended to know basics of using these tools, especially under a hypervisor setting where things are built upon further.
